version: '3'
services:
  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - db:/data/db
      - ./migrations/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  app:
    build: .
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
volumes:
  db: